// `pnpm gen:muscle-map` — build the static exercise→muscles map for the body diagram (PF-11). Reads our
// exercises (prod), matches each to free-exercise-db (same name matcher as the images), maps its
// primary/secondary muscles to react-body-highlighter keys, and WRITES a committed TS file. Reference
// data (universal, not per-studio), so it lives in the repo, not Firestore. Re-run to refresh.
import { initializeApp } from 'firebase-admin/app'
import { getFirestore } from 'firebase-admin/firestore'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

const PROJECT = process.env.GCLOUD_PROJECT ?? 'demo-sos'
if (!process.env.FIRESTORE_EMULATOR_HOST && !process.env.ALLOW_PRODUCTION) {
  console.error('Refusing to run against production without ALLOW_PRODUCTION=1.')
  process.exit(1)
}
const STUDIO = process.argv[2] ?? 'retro'

// Same overrides as exercise-images (our name → the free-db exercise name).
const OVERRIDE: Record<string, string> = {
  'Yürüyen Lunge': 'Walking Lunge', 'Leg Raise (Bacak Kaldırma)': 'Lying Leg Raise',
  'Calf Raise (Baldır)': 'Standing Calf Raises', 'Leg Curl (Yatarak)': 'Lying Leg Curls',
  'Abductor (Dış Kalça)': 'Thigh Abductor', 'Adductor (İç Bacak)': 'Thigh Adductor',
  'Pec Fly (Peck Deck)': 'Butterfly', 'Chest Press (Düz)': 'Dumbbell Bench Press',
  'Incline Chest Press': 'Incline Dumbbell Press', 'Lateral Raise': 'Side Lateral Raise',
  'Front Raise': 'Front Dumbbell Raise', 'Shoulder Press': 'Dumbbell Shoulder Press',
  'Dumbbell Biceps Curl': 'Dumbbell Bicep Curl', 'Single Arm Row': 'One-Arm Dumbbell Row',
  'Seated Cable Row': 'Seated Cable Rows', 'Lat Pulldown': 'Wide-Grip Lat Pulldown',
  'Sumo Squat': 'Plie Dumbbell Squat', Deadlift: 'Barbell Deadlift', 'Leg Extension': 'Leg Extensions',
  Crunch: 'Crunches', 'Cable Pull Through': 'Pull Through', 'Hip Thrust': 'Barbell Hip Thrust',
  Hyperextension: 'Hyperextensions', 'Bulgarian Split Squat': 'Split Squat with Dumbbells',
  'Cable Glute Kickback': 'Glute Kickback', 'Cable Woodchopper': 'Standing Cable Wood Chop',
  'Reverse Hack Squat': 'Hack Squat',
}
const tok = (s: string) => s.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(Boolean)
// free-exercise-db muscle → react-body-highlighter muscle key.
const M: Record<string, string> = {
  abdominals: 'abs', abductors: 'abductors', adductors: 'adductor', biceps: 'biceps', calves: 'calves',
  chest: 'chest', forearms: 'forearm', glutes: 'gluteal', hamstrings: 'hamstring', lats: 'upper-back',
  'lower back': 'lower-back', 'middle back': 'upper-back', neck: 'neck', quadriceps: 'quadriceps',
  shoulders: 'front-deltoids', traps: 'trapezius', triceps: 'triceps',
}
const mapMuscles = (arr: readonly string[]): string[] => [
  ...new Set(arr.map((m) => M[m]).filter((x): x is string => Boolean(x))),
]

async function main(): Promise<void> {
  initializeApp({ projectId: PROJECT })
  const db = getFirestore()
  const snap = await db.collection(`studios/${STUDIO}/exercises`).get()
  const ours = snap.docs.map((d) => (d.data().nameTr as string) ?? '').filter(Boolean)

  const res = await fetch('https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json')
  const dbEx = (await res.json()) as { name: string; primaryMuscles: string[]; secondaryMuscles: string[] }[]
  const dbTok = dbEx.map((e) => ({ e, t: new Set(tok(e.name)) }))
  const match = (name: string) => {
    const qt = tok(OVERRIDE[name] ?? name.replace(/\(.*?\)/g, ''))
    let best: { e: (typeof dbEx)[number]; extra: number } | null = null
    for (const { e, t } of dbTok) {
      if (!qt.every((x) => t.has(x))) continue
      const extra = t.size - qt.length
      if (!best || extra < best.extra) best = { e, extra }
    }
    return best?.e ?? null
  }

  const out: Record<string, { primary: string[]; secondary: string[] }> = {}
  for (const name of ours.sort()) {
    const m = match(name)
    if (!m) continue
    const primary = mapMuscles(m.primaryMuscles ?? [])
    const secondary = mapMuscles(m.secondaryMuscles ?? []).filter((x) => !primary.includes(x))
    if (primary.length === 0 && secondary.length === 0) continue
    out[name] = { primary, secondary }
  }

  const body =
    `// AUTO-GENERATED by tools/setup/gen-muscle-map.ts — do not edit by hand. Exercise nameTr → the muscles\n` +
    `// react-body-highlighter should paint (primary = bright red, secondary = light red). Source: free-\n` +
    `// exercise-db (public domain). PF-11.\nimport type { Muscle } from '@/components/muscle-map'\n\n` +
    `export const EXERCISE_MUSCLES: Record<string, { primary: Muscle[]; secondary: Muscle[] }> = ${JSON.stringify(out, null, 2)}\n`
  const dest = join(process.cwd(), 'apps/web/src/lib/exercise-muscles.ts')
  writeFileSync(dest, body)
  console.log(`✅ ${Object.keys(out).length}/${ours.length} egzersiz için kas haritası → apps/web/src/lib/exercise-muscles.ts`)
  process.exit(0)
}
void main()
