// AUTO-GENERATED by tools/setup/gen-muscle-map.ts — do not edit by hand. Exercise nameTr → the muscles
// react-body-highlighter should paint (primary = bright red, secondary = light red). Source: free-
// exercise-db (public domain). PF-11.
import type { Muscle } from '@/components/muscle-map'

export const EXERCISE_MUSCLES: Record<string, { primary: Muscle[]; secondary: Muscle[] }> = {
  "Abductor (Dış Kalça)": {
    "primary": [
      "abductors"
    ],
    "secondary": [
      "gluteal"
    ]
  },
  "Adductor (İç Bacak)": {
    "primary": [
      "adductor"
    ],
    "secondary": [
      "gluteal",
      "hamstring"
    ]
  },
  "Bulgarian Split Squat": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "gluteal",
      "hamstring"
    ]
  },
  "Cable Crunch": {
    "primary": [
      "abs"
    ],
    "secondary": []
  },
  "Cable Glute Kickback": {
    "primary": [
      "gluteal"
    ],
    "secondary": [
      "hamstring"
    ]
  },
  "Cable Pull Through": {
    "primary": [
      "gluteal"
    ],
    "secondary": [
      "hamstring",
      "lower-back"
    ]
  },
  "Cable Woodchopper": {
    "primary": [
      "abs"
    ],
    "secondary": [
      "front-deltoids"
    ]
  },
  "Calf Raise (Baldır)": {
    "primary": [
      "calves"
    ],
    "secondary": []
  },
  "Chest Press (Düz)": {
    "primary": [
      "chest"
    ],
    "secondary": [
      "front-deltoids",
      "triceps"
    ]
  },
  "Crunch": {
    "primary": [
      "abs"
    ],
    "secondary": []
  },
  "Deadlift": {
    "primary": [
      "lower-back"
    ],
    "secondary": [
      "calves",
      "forearm",
      "gluteal",
      "hamstring",
      "upper-back",
      "quadriceps",
      "trapezius"
    ]
  },
  "Dumbbell Biceps Curl": {
    "primary": [
      "biceps"
    ],
    "secondary": [
      "forearm"
    ]
  },
  "Face Pull": {
    "primary": [
      "front-deltoids"
    ],
    "secondary": [
      "upper-back"
    ]
  },
  "Front Raise": {
    "primary": [
      "front-deltoids"
    ],
    "secondary": []
  },
  "Glute Bridge (Kalça Köprüsü)": {
    "primary": [
      "gluteal"
    ],
    "secondary": [
      "calves",
      "hamstring"
    ]
  },
  "Goblet Squat": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "gluteal",
      "hamstring",
      "front-deltoids"
    ]
  },
  "Good Morning": {
    "primary": [
      "hamstring"
    ],
    "secondary": [
      "abs",
      "gluteal",
      "lower-back"
    ]
  },
  "Hack Squat": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "gluteal",
      "hamstring"
    ]
  },
  "Hammer Curl": {
    "primary": [
      "biceps"
    ],
    "secondary": [
      "forearm"
    ]
  },
  "Hip Thrust": {
    "primary": [
      "gluteal"
    ],
    "secondary": [
      "calves",
      "hamstring"
    ]
  },
  "Hyperextension": {
    "primary": [
      "lower-back"
    ],
    "secondary": [
      "gluteal",
      "hamstring"
    ]
  },
  "Incline Chest Press": {
    "primary": [
      "chest"
    ],
    "secondary": [
      "front-deltoids",
      "triceps"
    ]
  },
  "Lat Pulldown": {
    "primary": [
      "upper-back"
    ],
    "secondary": [
      "biceps",
      "front-deltoids"
    ]
  },
  "Lateral Raise": {
    "primary": [
      "front-deltoids"
    ],
    "secondary": []
  },
  "Leg Curl (Yatarak)": {
    "primary": [
      "hamstring"
    ],
    "secondary": []
  },
  "Leg Extension": {
    "primary": [
      "quadriceps"
    ],
    "secondary": []
  },
  "Leg Press": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "gluteal",
      "hamstring"
    ]
  },
  "Leg Raise (Bacak Kaldırma)": {
    "primary": [
      "abs"
    ],
    "secondary": []
  },
  "Pec Fly (Peck Deck)": {
    "primary": [
      "chest"
    ],
    "secondary": []
  },
  "Plank": {
    "primary": [
      "abs"
    ],
    "secondary": []
  },
  "Reverse Hack Squat": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "gluteal",
      "hamstring"
    ]
  },
  "Romanian Deadlift (RDL)": {
    "primary": [
      "hamstring"
    ],
    "secondary": [
      "calves",
      "gluteal",
      "lower-back"
    ]
  },
  "Russian Twist": {
    "primary": [
      "abs"
    ],
    "secondary": [
      "lower-back"
    ]
  },
  "Seated Cable Row": {
    "primary": [
      "upper-back"
    ],
    "secondary": [
      "biceps",
      "front-deltoids"
    ]
  },
  "Seated Leg Curl": {
    "primary": [
      "hamstring"
    ],
    "secondary": []
  },
  "Shoulder Press": {
    "primary": [
      "front-deltoids"
    ],
    "secondary": [
      "triceps"
    ]
  },
  "Single Arm Row": {
    "primary": [
      "upper-back"
    ],
    "secondary": [
      "biceps",
      "front-deltoids"
    ]
  },
  "Smith Machine Squat": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "gluteal",
      "hamstring",
      "lower-back"
    ]
  },
  "Step Up": {
    "primary": [
      "gluteal"
    ],
    "secondary": [
      "hamstring",
      "quadriceps"
    ]
  },
  "Sumo Squat": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "abs",
      "calves",
      "gluteal",
      "hamstring"
    ]
  },
  "Triceps Pushdown (Halat)": {
    "primary": [
      "triceps"
    ],
    "secondary": []
  },
  "Triceps Pushdown (V-Bar)": {
    "primary": [
      "triceps"
    ],
    "secondary": []
  },
  "Yürüyen Lunge": {
    "primary": [
      "quadriceps"
    ],
    "secondary": [
      "calves",
      "gluteal",
      "hamstring"
    ]
  }
}
